
import classes.Comment;
import classes.Issue;
import classes.Project;
import classes.Reactions;
import classes.User;
import database.CommentQuery;
import database.IssueQuery;
import database.ProjectQuery;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daryl Gan
 */
public class IssuePageGUI extends javax.swing.JFrame {
    
    protected static Scanner sc = new Scanner(System.in);

    protected static String opr;

    protected static User currentUser = new User( 4, "shawn", "shawn@gmail.com", "SHAWN" );

    protected static Project[] projects;
    protected static int selected_Project_ID;
    protected static Project currrentProject;

    protected static Issue[]   issues;
    protected static int selected_Issue_ID;
    protected static Issue currentIssue;

    /**
     * Creates new form IsuuePageGUI
     */
    public IssuePageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIssues = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtIssues = new javax.swing.JTextArea();
        jbBack1 = new javax.swing.JButton();
        jbStatus = new javax.swing.JButton();
        jbComments = new javax.swing.JButton();
        jbLog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue Tracker System - Issue Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIssues.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Issue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jIssues.setPreferredSize(new java.awt.Dimension(600, 350));

        jtIssues.setColumns(20);
        jtIssues.setRows(5);
        jScrollPane4.setViewportView(jtIssues);

        javax.swing.GroupLayout jIssuesLayout = new javax.swing.GroupLayout(jIssues);
        jIssues.setLayout(jIssuesLayout);
        jIssuesLayout.setHorizontalGroup(
            jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIssuesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        jIssuesLayout.setVerticalGroup(
            jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIssuesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jIssues, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 550, 300));
        jIssues.getAccessibleContext().setAccessibleName("Issue");

        jbBack1.setText("Back");
        jbBack1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbBack1.setMaximumSize(new java.awt.Dimension(65, 25));
        jbBack1.setMinimumSize(new java.awt.Dimension(65, 25));
        jbBack1.setPreferredSize(new java.awt.Dimension(65, 25));
        jbBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, -1));

        jbStatus.setText("Status");
        jbStatus.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbStatus.setMaximumSize(new java.awt.Dimension(70, 25));
        jbStatus.setMinimumSize(new java.awt.Dimension(70, 25));
        jbStatus.setPreferredSize(new java.awt.Dimension(70, 25));
        jbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(jbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, -1));

        jbComments.setText("<html>View<br>Comments</html>");
        jbComments.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbComments.setMaximumSize(new java.awt.Dimension(70, 25));
        jbComments.setMinimumSize(new java.awt.Dimension(70, 25));
        jbComments.setPreferredSize(new java.awt.Dimension(70, 25));
        jbComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCommentsActionPerformed(evt);
            }
        });
        getContentPane().add(jbComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 100, 40));

        jbLog.setText("Log");
        jbLog.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbLog.setMaximumSize(new java.awt.Dimension(65, 25));
        jbLog.setMinimumSize(new java.awt.Dimension(65, 25));
        jbLog.setPreferredSize(new java.awt.Dimension(65, 25));
        jbLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogActionPerformed(evt);
            }
        });
        getContentPane().add(jbLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 70, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCommentsActionPerformed
        CommentsGUI2 commt = new CommentsGUI2();
        commt.setVisible(true);
        dispose();
        
        commt.display();
    }//GEN-LAST:event_jbCommentsActionPerformed

    private void jbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStatusActionPerformed
//        int currentUserID = currentUser.getUserID();
//        int creatorID     = currentIssue.getCreator().getUserID();
//        int assigneeID    = currentIssue.getAssignee().getUserID();
        
//testing
        try {
        selected_Project_ID = 1;
        currrentProject     = ProjectQuery.getProject(selected_Project_ID);
        }
        catch (SQLException | ClassNotFoundException a){
            
        }
        
        try {
        selected_Issue_ID   = 1;
        currentIssue        = IssueQuery.getIssue( selected_Issue_ID );
        }
        catch (SQLException | ClassNotFoundException a){
            
        }
       
        int currentUserID = 6;
        int creatorID     = 6;
        int assigneeID    = 7;
//testing

        String[] newStatus;
        
        if (currentUserID == assigneeID) {
            newStatus = new String[]{"Open", "In Progress", "Resolved", "Closed"};
            changeStatus(newStatus);
        }
        else if (currentUserID == creatorID) {
            newStatus = new String[]{"Open", "Resolved", "Closed"};
            changeStatus(newStatus);
        }
        else {
            JOptionPane.showMessageDialog(
                this,
                "You are not allowed to CHANGE the STATUS of this issue!",
                "Status Change Error",
                JOptionPane.WARNING_MESSAGE
            );
        }
        
        
    }//GEN-LAST:event_jbStatusActionPerformed

    void changeStatus(String[] newStatus) {
        String status = (String)JOptionPane.showInputDialog(
                this,
                "Choose new status of current issue: ",
                "Status Change",
                JOptionPane.QUESTION_MESSAGE,
                null,
                newStatus,
                newStatus[0]           
            );
        
            JOptionPane.showMessageDialog(
                this,
                "You have changed the status to: " + status,
                "Status Changed",
                JOptionPane.INFORMATION_MESSAGE
            );
        
            try {
                IssueQuery.updateStatus(currentIssue.getIssueID(), status);
            }
                catch (SQLException | ClassNotFoundException a){

            }
            
            jtIssues.setText("");
            display();
    }
    
    private void jbLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogActionPerformed
        //viewChangeLog();
    }//GEN-LAST:event_jbLogActionPerformed

    private void jbBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBack1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbBack1ActionPerformed

        void display() {
//testing
        try {
        selected_Project_ID = 1;
        currrentProject     = ProjectQuery.getProject(selected_Project_ID);
        }
        catch (SQLException | ClassNotFoundException a){
            
        }
        
        try {
        selected_Issue_ID   = 1;
        currentIssue        = IssueQuery.getIssue( selected_Issue_ID );
        }
        catch (SQLException | ClassNotFoundException a){
            
        }
       
        int currentUserID = 6;
        int creatorID     = 6;
        int assigneeID    = 7;
//testing
            
            StringBuilder sb = new StringBuilder("");

            sb.append(String.format("%-20s%-50s\n", "Title:"         , currentIssue.getTitle()));
            sb.append(String.format("%-20s%-50s\n", "Issue ID:"      , currentIssue.getIssueID()));
            sb.append(String.format("%-20s%-50s\n", "Status:"        , currentIssue.getStatus()));
            sb.append(String.format("%-20s%-50s\n", "Tag:"           , currentIssue.getTag()));
            sb.append(String.format("%-20s%-50d\n", "Priority:"      , currentIssue.getPriority()));
            sb.append(String.format("%-20s%-50s\n", "Created on:"    , currentIssue.getTime().toString()));
            sb.append(String.format("%-20s%-50s\n", "Created by:"    , currentIssue.getCreator().getName()));
            sb.append(String.format("%-20s%-50s\n", "Assigned to:"   , currentIssue.getAssignee().getName()));
            sb.append("\n");

            String issueDescription  = "Description:";
            sb.append("-".repeat(issueDescription.length())).append("\n");
            sb.append(issueDescription).append("\n");
            sb.append("-".repeat(issueDescription.length())).append("\n");
            sb.append( currentIssue.getDescription() );

            jtIssues.append(sb.toString());
            jtIssues.setEditable(false);
        }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
                IssuePageGUI issue = new IssuePageGUI();
                issue.setVisible(true);
                issue.display();      
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jIssues;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbBack1;
    private javax.swing.JButton jbComments;
    private javax.swing.JButton jbLog;
    private javax.swing.JButton jbStatus;
    private javax.swing.JTextArea jtIssues;
    // End of variables declaration//GEN-END:variables
}
