package operations;

import classes.Issue;
import classes.User;
import database.IssueQuery;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daryl Gan
 */
public class IssuePageGUI extends javax.swing.JFrame {
    

    protected static User currentUser ;
    protected static int selected_Issue_ID;
    protected static Issue currentIssue;

    /**
     * Creates new form IsuuePageGUI
     */
    public IssuePageGUI( int issueID, User currentUser) throws SQLException, ClassNotFoundException {
        initComponents();
        selected_Issue_ID=issueID;
        this.currentUser=currentUser;
        currentIssue=IssueQuery.getIssue(selected_Issue_ID);
        this.setLocationRelativeTo(null);
        this.setTitle("Bugs Everywhere SDN BHD");
        display();
    }
    
    public void display() {

        try {
        currentIssue        = IssueQuery.getIssue( selected_Issue_ID );
        }
        catch (SQLException | ClassNotFoundException a){
            
        }
       
            jTtitle.setText(currentIssue.getTitle());
            jTissueID.setText(String.valueOf(currentIssue.getIssueID()));
            jTstatus.setText(currentIssue.getStatus());
            jTtag.setText(currentIssue.getTag());
            jTpriority.setText(String.valueOf(currentIssue.getPriority()));
            jTdate.setText(currentIssue.getTime().toString());
            jTcreator.setText(currentIssue.getCreator().getName());
            jTassignee.setText(currentIssue.getAssignee().getName());
            
            jtissueDescription.setText(currentIssue.getDescription());
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIssues = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTtitle = new javax.swing.JTextField();
        jTassignee = new javax.swing.JTextField();
        jTcreator = new javax.swing.JTextField();
        jTissueID = new javax.swing.JTextField();
        jTtag = new javax.swing.JTextField();
        jTstatus = new javax.swing.JTextField();
        jTdate = new javax.swing.JTextField();
        jTpriority = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtissueDescription = new javax.swing.JTextArea();
        jbBack1 = new javax.swing.JButton();
        jbStatus = new javax.swing.JButton();
        jbComments = new javax.swing.JButton();
        jbchangelog = new javax.swing.JButton();
        jbeditDes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Issue Tracker System - Issue Page");

        jIssues.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Issue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jIssues.setPreferredSize(new java.awt.Dimension(600, 350));

        jLabel1.setText("Title:");

        jLabel2.setText("Issue ID:");

        jLabel3.setText("Tag:");

        jLabel4.setText("Status:");

        jLabel5.setText("Priority:");

        jLabel7.setText("Created on:");

        jLabel8.setText("Created by:");
        jLabel8.setToolTipText("");

        jLabel9.setText("Assigned to:");

        jTtitle.setEditable(false);
        jTtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtitleActionPerformed(evt);
            }
        });

        jTassignee.setEditable(false);
        jTassignee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTassigneeActionPerformed(evt);
            }
        });

        jTcreator.setEditable(false);
        jTcreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcreatorActionPerformed(evt);
            }
        });

        jTissueID.setEditable(false);
        jTissueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTissueIDActionPerformed(evt);
            }
        });

        jTtag.setEditable(false);
        jTtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtagActionPerformed(evt);
            }
        });

        jTstatus.setEditable(false);
        jTstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTstatusActionPerformed(evt);
            }
        });

        jTdate.setEditable(false);
        jTdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdateActionPerformed(evt);
            }
        });

        jTpriority.setEditable(false);
        jTpriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpriorityActionPerformed(evt);
            }
        });

        jLabel6.setText("Description: ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtissueDescription.setEditable(false);
        jtissueDescription.setColumns(5);
        jtissueDescription.setRows(5);
        jScrollPane1.setViewportView(jtissueDescription);
        jtissueDescription.setLineWrap(true);

        javax.swing.GroupLayout jIssuesLayout = new javax.swing.GroupLayout(jIssues);
        jIssues.setLayout(jIssuesLayout);
        jIssuesLayout.setHorizontalGroup(
            jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIssuesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jIssuesLayout.createSequentialGroup()
                        .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTissueID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTassignee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTcreator, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTtag, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTpriority, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jIssuesLayout.createSequentialGroup()
                                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jIssuesLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTdate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 158, Short.MAX_VALUE))))
                    .addComponent(jTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jIssuesLayout.setVerticalGroup(
            jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIssuesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTissueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jIssuesLayout.createSequentialGroup()
                        .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTpriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTcreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTassignee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jbBack1.setText("Back");
        jbBack1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbBack1.setMaximumSize(new java.awt.Dimension(65, 25));
        jbBack1.setMinimumSize(new java.awt.Dimension(65, 25));
        jbBack1.setPreferredSize(new java.awt.Dimension(65, 25));
        jbBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBack1ActionPerformed(evt);
            }
        });

        jbStatus.setText("<html>Change<br>Status</html>");
        jbStatus.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbStatus.setMaximumSize(new java.awt.Dimension(70, 25));
        jbStatus.setMinimumSize(new java.awt.Dimension(70, 25));
        jbStatus.setPreferredSize(new java.awt.Dimension(70, 25));
        jbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStatusActionPerformed(evt);
            }
        });

        jbComments.setText("<html>View<br>Comments</html>");
        jbComments.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbComments.setMaximumSize(new java.awt.Dimension(70, 25));
        jbComments.setMinimumSize(new java.awt.Dimension(70, 25));
        jbComments.setPreferredSize(new java.awt.Dimension(70, 25));
        jbComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCommentsActionPerformed(evt);
            }
        });

        jbchangelog.setText("<html>View<br>Changelog</html>");
        jbchangelog.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbchangelog.setMaximumSize(new java.awt.Dimension(65, 25));
        jbchangelog.setMinimumSize(new java.awt.Dimension(65, 25));
        jbchangelog.setPreferredSize(new java.awt.Dimension(65, 25));
        jbchangelog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbchangelogActionPerformed(evt);
            }
        });

        jbeditDes.setText("<html>Edit<br>Description</html>");
        jbeditDes.setToolTipText("");
        jbeditDes.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jbeditDes.setMaximumSize(new java.awt.Dimension(65, 25));
        jbeditDes.setMinimumSize(new java.awt.Dimension(65, 25));
        jbeditDes.setPreferredSize(new java.awt.Dimension(65, 25));
        jbeditDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeditDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbComments, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbeditDes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jbchangelog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jIssues, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbComments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbeditDes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbchangelog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBack1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCommentsActionPerformed
        CommentsGUI2 commt = new CommentsGUI2(selected_Issue_ID,currentUser);
        commt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCommentsActionPerformed

    private void jbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStatusActionPerformed

        int currentUserID = currentUser.getUserID();
        int creatorID     = currentIssue.getCreator().getUserID();
        int assigneeID    = currentIssue.getAssignee().getUserID();


        String[] newStatus;
        
        if (currentUserID == assigneeID) {
            newStatus = new String[]{"Open", "In Progress", "Resolved", "Closed"};
            changeStatus(newStatus);
        }
        else if (currentUserID == creatorID) {
            newStatus = new String[]{"Open", "Resolved", "Closed"};
            changeStatus(newStatus);
        }
        else {
            JOptionPane.showMessageDialog(
                this,
                "You are not allowed to CHANGE the STATUS of this issue!",
                "Status Change Error",
                JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_jbStatusActionPerformed

    public void changeStatus(String[] newStatus) {
        String status = (String)JOptionPane.showInputDialog(
                this,
                "Choose new status of current issue: ",
                "Status Change",
                JOptionPane.QUESTION_MESSAGE,
                null,
                newStatus,
                newStatus[0]           
            );
        
        
            try {
                if(status!=null){
                    IssueQuery.updateStatus(currentIssue.getIssueID(), status);
                    JOptionPane.showMessageDialog(
                        this,
                        "You have changed the status to: " + status,
                        "Status Changed",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    
                }
            }
                catch (SQLException | ClassNotFoundException a){

            }
            
            display();
    }
    
    private void jbchangelogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbchangelogActionPerformed
        Issue[] previousIssues=null;
        try {
            previousIssues = IssueQuery.getPreviousIssues( selected_Issue_ID );
            
            if (previousIssues.length == 0)
                JOptionPane.showMessageDialog(null, "No changes made!");
            else{
                IssueDesChangeLog idcl=new IssueDesChangeLog(selected_Issue_ID,currentUser);
                idcl.setVisible(true);
                this.dispose();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jbchangelogActionPerformed

    private void jbBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBack1ActionPerformed
        try {
            IssueDashboard issueD=new IssueDashboard(currentIssue.getProjectID(),currentUser);
            issueD.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbBack1ActionPerformed

    private void jbeditDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeditDesActionPerformed
        EditIssueDescription edit;
        int currentUserID = currentUser.getUserID();
        int creatorID     = currentIssue.getCreator().getUserID();
        if (currentUserID == creatorID){
            try {
                edit = new EditIssueDescription(selected_Issue_ID,currentUser);
                edit.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "You are not allowed to change this issue description!");
    }//GEN-LAST:event_jbeditDesActionPerformed

    private void jTtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtitleActionPerformed

    private void jTtagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtagActionPerformed

    private void jTdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdateActionPerformed

    private void jTissueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTissueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTissueIDActionPerformed

    private void jTstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTstatusActionPerformed

    private void jTpriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpriorityActionPerformed

    private void jTcreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcreatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcreatorActionPerformed

    private void jTassigneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTassigneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTassigneeActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
                try {
                    IssuePageGUI issue = new IssuePageGUI(selected_Issue_ID,currentUser);
                } catch (SQLException ex) {
                    Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(IssuePageGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jIssues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTassignee;
    private javax.swing.JTextField jTcreator;
    private javax.swing.JTextField jTdate;
    private javax.swing.JTextField jTissueID;
    private javax.swing.JTextField jTpriority;
    private javax.swing.JTextField jTstatus;
    private javax.swing.JTextField jTtag;
    private javax.swing.JTextField jTtitle;
    private javax.swing.JButton jbBack1;
    private javax.swing.JButton jbComments;
    private javax.swing.JButton jbStatus;
    private javax.swing.JButton jbchangelog;
    private javax.swing.JButton jbeditDes;
    private javax.swing.JTextArea jtissueDescription;
    // End of variables declaration//GEN-END:variables
}
